// This file was autogenerated by F:\Users\inage.toru\Workspaces\workspace-e3.7-x64-js\example-closure/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../WebContent/scripts/example/app.js', ['example.App'], ['example.RoadRunner', 'goog.dom', 'goog.events']);
goog.addDependency('../../../WebContent/scripts/example/car.js', ['example.Car'], []);
goog.addDependency('../../../WebContent/scripts/example/roadrunner.js', ['example.RoadRunner'], ['example.Car']);
